name: Deploy to EC2

on:
  push:
    branches:
      - main  # Atau branch yang Anda inginkan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install 

      - name: Run tests
        run: npm test

      - name: Deploy to EC2 via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} $EC2_USER@$EC2_HOST << 'EOF'
            cd project/f-bee24001186-km7-dev-basicbankingsystem-ch2
            git pull origin main
            npm install
            npm run build
            pm2 restart all || pm2 start app.js --name "my-app"
            pm2 startup systemd
            pm2 save
          EOF
