name: Deploy to EC2

on:
  push:
    branches:
      - main  # Branch yang akan memicu deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout kode
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Langkah 3: Deploy ke EC2, install dependencies, dan restart aplikasi
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Pindah ke direktori proyek
            cd ~/project/f-bee24001186-km7-dev-basicbankingsystem-ch2/src

            # Pull perubahan terbaru dari branch main
            git pull origin main

            # Install dependencies proyek
            npm install

            # Generate Prisma client
            npx prisma generate

            # Restart aplikasi dengan PM2 atau mulai jika belum berjalan
            pm2 restart "BankAccounts" || pm2 start index.js --name "BankAccounts"

            # Simpan daftar dan konfigurasi proses PM2
            pm2 save

            # Menambahkan PM2 ke startup agar otomatis berjalan saat server reboot
            pm2 startup systemd --hp /home/ubuntu
            pm2 save
          EOF
